# agent_llm_prompts.py
# 存放所有prompt模板和相关函数，便于维护和复用

# 获取不同任务类型的英文prompt模板

def get_task_prompt_template(task_type: str) -> str:
    """
    Return the English prompt template for the given task_type.
    """
    if task_type == "LaMP_1_time" or task_type == "LaMP_1":
        task_type = "citation"
    elif task_type == "LaMP_2_time" or task_type == "LaMP_2":
        task_type = "movie"
    elif task_type == "LaMP_3_time" or task_type == "LaMP_3":
        task_type = "product"
    elif task_type == "LaMP_4_time" or task_type == "LaMP_4":
        task_type = "news"
    elif task_type == "LaMP_5_time" or task_type == "LaMP_5":
        task_type = "academic"
    elif task_type == "LaMP_6_time" or task_type == "LaMP_6":
        task_type = "email"
    elif task_type == "LaMP_7_time" or task_type == "LaMP_7":
        task_type = "tweet"

    templates = {
        "citation": (
            "You are an expert in academic citation analysis. Based on the user's previously published paper titles and abstracts, summarize the user's research interests and citation preferences in a structured JSON format.\n\n"
            "**Current User Feature Summary (JSON):**\n{summary}\n\n"
            "**New User Records ({n_records}):**\n{records_md}\n\n"
            "**Task:**\nUpdate the user's research interests and citation preferences in JSON format, reflecting any new information from the records. "
            "The JSON should include (but is not limited to) the following fields: "
            "- 'main_disciplines': Main academic disciplines (e.g., Computer Science, Biology).\n"
            "- 'subfields': Subfields or specific research directions.\n"
            "- 'common_methods': Frequently used research methods.\n"
            "- 'application_domains': Application areas.\n"
            "- 'frequent_keywords': Commonly used keywords.\n"
            "- 'preferred_journals_conferences': Frequently published/cited journals and conferences.\n"
            "- 'citation_style': Citation style or preferences.\n"
            "- 'preferred_citation_types': Preferred types of citations (e.g., review, original research).\n"
            "- 'frequent_cited_authors': Frequently cited authors.\n"
            "- 'recent_self_citation_ratio': Recent self-citation ratio.\n"
            "- 'literature_recency_preference': Preference for new or old literature.\n"
            "- 'open_access_preference': Open access preference.\n"
            "- 'citation_languages': Languages of cited literature.\n"
            "- 'interdisciplinary_tendency': Tendency for interdisciplinary citations.\n"
            "Only output the updated JSON."
        ),
        "movie": (
            "You are a movie preference analysis expert. Based on the user's historical movie tagging behavior and movie descriptions, summarize the user's favorite genres, themes, and tagging patterns in a structured JSON format.\n\n"
            "**Current User Feature Summary (JSON):**\n{summary}\n\n"
            "**New User Records ({n_records}):**\n{records_md}\n\n"
            "**Task:**\nUpdate the user's movie preference features in JSON format, reflecting any new information from the records. "
            "The JSON should include (but is not limited to) the following fields: "
            "- 'favorite_genres': List of favorite movie genres.\n"
            "- 'favorite_themes': List of favorite themes.\n"
            "- 'favorite_actors': List of favorite actors/actresses.\n"
            "- 'recently_watched': List of recently watched movies.\n"
            "- 'tagging_patterns': Description of tagging or rating patterns.\n"
            "- 'average_rating': Average rating given by the user.\n"
            "- 'language_preference': Preferred movie languages.\n"
            "- 'watching_time_distribution': Distribution of watching time (e.g., weekends, nights).\n"
            "Only output the updated JSON."
        ),
        "product": (
            "You are a product preference analysis expert. Based on the user's historical product reviews and ratings, summarize the user's product preferences, rating tendencies, and key concerns in a structured JSON format.\n\n"
            "**Current User Feature Summary (JSON):**\n{summary}\n\n"
            "**New User Records ({n_records}):**\n{records_md}\n\n"
            "**Task:**\nUpdate the user's product preference features in JSON format, reflecting any new information from the records. "
            "The JSON should include (but is not limited to) the following fields: "
            "- 'favorite_categories': List of favorite product categories.\n"
            "- 'brand_preferences': List of preferred brands.\n"
            "- 'price_sensitivity': Description of price sensitivity (e.g., prefers budget, mid-range, premium).\n"
            "- 'key_concerns': List of key concerns (e.g., quality, delivery, after-sales).\n"
            "- 'average_rating': Average rating given by the user.\n"
            "- 'purchase_frequency': Purchase frequency.\n"
            "- 'review_style': Review style or tendencies.\n"
            "Only output the updated JSON."
        ),
        "news": (
            "You are a news headline generation expert. Based on the author's historical news headlines, summarize the author's headline writing style and preferences in a structured JSON format.\n\n"
            "**Current User Feature Summary (JSON):**\n{summary}\n\n"
            "**New User Records ({n_records}):**\n{records_md}\n\n"
            "**Task:**\nUpdate the author's headline style features in JSON format, reflecting any new information from the records. "
            "The JSON should include (but is not limited to) the following fields: "
            "- 'preferred_topics': Preferred news topics.\n"
            "- 'headline_style': Description of headline style (e.g., sensational, objective).\n"
            "- 'language_features': Notable language features.\n"
            "- 'length_preference': Preferred headline length.\n"
            "- 'recent_headlines': List of recent headlines.\n"
            "Only output the updated JSON."
        ),
        "academic": (
            "You are an academic title generation expert. Based on the author's historical academic paper titles, summarize the author's title writing style and preferences in a structured JSON format.\n\n"
            "**Current User Feature Summary (JSON):**\n{summary}\n\n"
            "**New User Records ({n_records}):**\n{records_md}\n\n"
            "**Task:**\nUpdate the author's academic title style features in JSON format, reflecting any new information from the records. "
            "The JSON should include (but is not limited to) the following fields: "
            "- 'main_disciplines': Main academic disciplines.\n"
            "- 'title_style': Description of title style (e.g., concise, descriptive).\n"
            "- 'common_keywords': Commonly used keywords.\n"
            "- 'length_preference': Preferred title length.\n"
            "- 'recent_titles': List of recent titles.\n"
            "Only output the updated JSON."
        ),
        "email": (
            "You are an email subject generation expert. Based on the user's historical email subjects, summarize the user's subject writing style and preferences in a structured JSON format.\n\n"
            "**Current User Feature Summary (JSON):**\n{summary}\n\n"
            "**New User Records ({n_records}):**\n{records_md}\n\n"
            "**Task:**\nUpdate the user's email subject style features in JSON format, reflecting any new information from the records. "
            "The JSON should include (but is not limited to) the following fields: "
            "- 'subject_style': Description of subject style.\n"
            "- 'preferred_topics': Preferred email topics.\n"
            "- 'length_preference': Preferred subject length.\n"
            "- 'recent_subjects': List of recent email subjects.\n"
            "Only output the updated JSON."
        ),
        "tweet": (
            "You are a tweet style analysis expert. Based on the user's historical tweets, summarize the user's language style, tone, and expression patterns in a structured JSON format.\n\n"
            "**Current User Feature Summary (JSON):**\n{summary}\n\n"
            "**New User Records ({n_records}):**\n{records_md}\n\n"
            "**Task:**\nUpdate the user's tweet style features in JSON format, reflecting any new information from the records. "
            "The JSON should include (but is not limited to) the following fields: "
            "- 'language_style': Description of language style.\n"
            "- 'tone': Typical tone (e.g., humorous, serious).\n"
            "- 'expression_patterns': Common expression patterns.\n"
            "- 'frequent_topics': Frequent tweet topics.\n"
            "- 'recent_tweets': List of recent tweets.\n"
            "Only output the updated JSON."
        ),
    }
    # Default prompt if task_type is None or unknown
    default_prompt = (
        "You are an expert at summarizing user preferences. Please update the user's preference summary step by step based on their historical records.\n\n"
        "**Current User Feature Summary (JSON):**\n{summary}\n\n"
        "**New User Records ({n_records}):**\n{records_md}\n\n"
        "**Task:**\nUpdate the user preference summary in concise English, using JSON format. Only output the updated JSON."
    )
    return templates.get(task_type, default_prompt)


def get_task_toolcall_prompt_template(task_type: str) -> str:
    """
    Return the English tool_call prompt template for the given task_type.
    """
    templates = {
        "citation": (
            "You are an expert in academic citation analysis. Your job is to update the user's research interests and citation preferences step by step based on their historical records, using a set of tools.\n\n"
            "**Current User Feature Summary (JSON):**\n{summary}\n\n"
            "**New User Records ({n_records}):**\n{records_md}\n\n"
            "**Task:**\nAnalyze the new records and update the user's preference fields in the JSON summary. Output your decisions as a sequence of tool calls, one per line, using the following format:\n\n"
            "ToolName(field_name, value)\n\n"
            "Available tools:\n"
            "- add_field(field_name, value): Add a value to a list field (e.g., add to main_disciplines)\n"
            "- delete_field(field_name, value): Remove a value from a list field\n"
            "- update_field(field_name, old_value, new_value): Replace an old value with a new one\n"
            "- set_field(field_name, value): Set a field to a specific value\n\n"
            "Common fields for citation task:\n"
            "- main_disciplines: Main academic disciplines (e.g., Computer Science, Biology)\n"
            "- subfields: Subfields or specific research directions\n"
            "- common_methods: Frequently used research methods\n"
            "- application_domains: Application areas\n"
            "- frequent_keywords: Commonly used keywords\n"
            "- preferred_journals_conferences: Frequently published/cited journals and conferences\n"
            "- citation_style: Citation style or preferences\n"
            "- preferred_citation_types: Preferred types of citations\n"
            "- frequent_cited_authors: Frequently cited authors\n"
            "- recent_self_citation_ratio: Recent self-citation ratio\n"
            "- literature_recency_preference: Preference for new or old literature\n"
            "- open_access_preference: Open access preference\n"
            "- citation_languages: Languages of cited literature\n"
            "- interdisciplinary_tendency: Tendency for interdisciplinary citations\n\n"
            "Only output tool calls, do not output any explanation or summary."
        ),
        "movie": (
            "You are a movie preference analysis expert. Your job is to update the user's movie preference summary step by step based on their historical records, using a set of tools.\n\n"
            "**Current User Feature Summary (JSON):**\n{summary}\n\n"
            "**New User Records ({n_records}):**\n{records_md}\n\n"
            "**Task:**\nAnalyze the new records and update the user's preference fields in the JSON summary. Output your decisions as a sequence of tool calls, one per line, using the following format:\n\n"
            "ToolName(field_name, value)\n\n"
            "Available tools:\n"
            "- add_field(field_name, value): Add a value to a list field (e.g., add to favorite_genres)\n"
            "- delete_field(field_name, value): Remove a value from a list field\n"
            "- update_field(field_name, old_value, new_value): Replace an old value with a new one\n"
            "- set_field(field_name, value): Set a field to a specific value\n\n"
            "Common fields for movie task:\n"
            "- favorite_genres: List of favorite movie genres\n"
            "- favorite_themes: List of favorite themes\n"
            "- favorite_actors: List of favorite actors/actresses\n"
            "- recently_watched: List of recently watched movies\n"
            "- tagging_patterns: Description of tagging or rating patterns\n"
            "- average_rating: Average rating given by the user\n"
            "- language_preference: Preferred movie languages\n"
            "- watching_time_distribution: Distribution of watching time\n\n"
            "Only output tool calls, do not output any explanation or summary."
        ),
        "product": (
            "You are a product preference analysis expert. Your job is to update the user's product preference summary step by step based on their historical records, using a set of tools.\n\n"
            "**Current User Feature Summary (JSON):**\n{summary}\n\n"
            "**New User Records ({n_records}):**\n{records_md}\n\n"
            "**Task:**\nAnalyze the new records and update the user's preference fields in the JSON summary. Output your decisions as a sequence of tool calls, one per line, using the following format:\n\n"
            "ToolName(field_name, value)\n\n"
            "Available tools:\n"
            "- add_field(field_name, value): Add a value to a list field (e.g., add to favorite_categories)\n"
            "- delete_field(field_name, value): Remove a value from a list field\n"
            "- update_field(field_name, old_value, new_value): Replace an old value with a new one\n"
            "- set_field(field_name, value): Set a field to a specific value\n\n"
            "Common fields for product task:\n"
            "- favorite_categories: List of favorite product categories\n"
            "- brand_preferences: List of preferred brands\n"
            "- price_sensitivity: Description of price sensitivity\n"
            "- key_concerns: List of key concerns\n"
            "- average_rating: Average rating given by the user\n"
            "- purchase_frequency: Purchase frequency\n"
            "- review_style: Review style or tendencies\n\n"
            "Only output tool calls, do not output any explanation or summary."
        ),
        "news": (
            "You are a news headline generation expert. Your job is to update the author's headline style features step by step based on their historical records, using a set of tools.\n\n"
            "**Current User Feature Summary (JSON):**\n{summary}\n\n"
            "**New User Records ({n_records}):**\n{records_md}\n\n"
            "**Task:**\nAnalyze the new records and update the author's style fields in the JSON summary. Output your decisions as a sequence of tool calls, one per line, using the following format:\n\n"
            "ToolName(field_name, value)\n\n"
            "Available tools:\n"
            "- add_field(field_name, value): Add a value to a list field\n"
            "- delete_field(field_name, value): Remove a value from a list field\n"
            "- update_field(field_name, old_value, new_value): Replace an old value with a new one\n"
            "- set_field(field_name, value): Set a field to a specific value\n\n"
            "Common fields for news task:\n"
            "- preferred_topics: Preferred news topics\n"
            "- headline_style: Description of headline style\n"
            "- language_features: Notable language features\n"
            "- length_preference: Preferred headline length\n"
            "- recent_headlines: List of recent headlines\n\n"
            "Only output tool calls, do not output any explanation or summary."
        ),
        "academic": (
            "You are an academic title generation expert. Your job is to update the author's academic title style features step by step based on their historical records, using a set of tools.\n\n"
            "**Current User Feature Summary (JSON):**\n{summary}\n\n"
            "**New User Records ({n_records}):**\n{records_md}\n\n"
            "**Task:**\nAnalyze the new records and update the author's style fields in the JSON summary. Output your decisions as a sequence of tool calls, one per line, using the following format:\n\n"
            "ToolName(field_name, value)\n\n"
            "Available tools:\n"
            "- add_field(field_name, value): Add a value to a list field\n"
            "- delete_field(field_name, value): Remove a value from a list field\n"
            "- update_field(field_name, old_value, new_value): Replace an old value with a new one\n"
            "- set_field(field_name, value): Set a field to a specific value\n\n"
            "Common fields for academic task:\n"
            "- main_disciplines: Main academic disciplines\n"
            "- title_style: Description of title style\n"
            "- common_keywords: Commonly used keywords\n"
            "- length_preference: Preferred title length\n"
            "- recent_titles: List of recent titles\n\n"
            "Only output tool calls, do not output any explanation or summary."
        ),
        "email": (
            "You are an email subject generation expert. Your job is to update the user's email subject style features step by step based on their historical records, using a set of tools.\n\n"
            "**Current User Feature Summary (JSON):**\n{summary}\n\n"
            "**New User Records ({n_records}):**\n{records_md}\n\n"
            "**Task:**\nAnalyze the new records and update the user's style fields in the JSON summary. Output your decisions as a sequence of tool calls, one per line, using the following format:\n\n"
            "ToolName(field_name, value)\n\n"
            "Available tools:\n"
            "- add_field(field_name, value): Add a value to a list field\n"
            "- delete_field(field_name, value): Remove a value from a list field\n"
            "- update_field(field_name, old_value, new_value): Replace an old value with a new one\n"
            "- set_field(field_name, value): Set a field to a specific value\n\n"
            "Common fields for email task:\n"
            "- subject_style: Description of subject style\n"
            "- preferred_topics: Preferred email topics\n"
            "- length_preference: Preferred subject length\n"
            "- recent_subjects: List of recent email subjects\n\n"
            "Only output tool calls, do not output any explanation or summary."
        ),
        "tweet": (
            "You are a tweet style analysis expert. Your job is to update the user's tweet style features step by step based on their historical records, using a set of tools.\n\n"
            "**Current User Feature Summary (JSON):**\n{summary}\n\n"
            "**New User Records ({n_records}):**\n{records_md}\n\n"
            "**Task:**\nAnalyze the new records and update the user's style fields in the JSON summary. Output your decisions as a sequence of tool calls, one per line, using the following format:\n\n"
            "ToolName(field_name, value)\n\n"
            "Available tools:\n"
            "- add_field(field_name, value): Add a value to a list field\n"
            "- delete_field(field_name, value): Remove a value from a list field\n"
            "- update_field(field_name, old_value, new_value): Replace an old value with a new one\n"
            "- set_field(field_name, value): Set a field to a specific value\n\n"
            "Common fields for tweet task:\n"
            "- language_style: Description of language style\n"
            "- tone: Typical tone (e.g., humorous, serious)\n"
            "- expression_patterns: Common expression patterns\n"
            "- frequent_topics: Frequent tweet topics\n"
            "- recent_tweets: List of recent tweets\n\n"
            "Only output tool calls, do not output any explanation or summary."
        ),
    }
    default_prompt = (
        "You are an expert at summarizing user preferences. Your job is to update the user's preference summary step by step based on their historical records, using a set of tools.\n\n"
        "**Current User Feature Summary (JSON):**\n{summary}\n\n"
        "**New User Records ({n_records}):**\n{records_md}\n\n"
        "**Task:**\nAnalyze the new records and update the user's preference fields in the JSON summary. Output your decisions as a sequence of tool calls, one per line, using the following format:\n\n"
        "ToolName(field_name, value)\n\n"
        "Available tools:\n"
        "- add_field(field_name, value): Add a value to a list field\n"
        "- delete_field(field_name, value): Remove a value from a list field\n"
        "- update_field(field_name, old_value, new_value): Replace an old value with a new one\n"
        "- set_field(field_name, value): Set a field to a specific value\n\n"
        "Only output tool calls, do not output any explanation or summary."
    )
    return templates.get(task_type, default_prompt) 